/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입 (이메일+비밀번호)
         * @description 이메일/비밀번호로 새 계정 생성 후 access_token 즉시 발급.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인 (이메일+비밀번호)
         * @description 이메일/비밀번호 검증 후 access_token 발급.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google 소셜 로그인
         * @description Google ID token으로 로그인 또는 자동 회원가입.
         *
         *     신규 사용자는 자동 가입 후 201 Created, 기존 사용자는 200 OK 반환.
         *     FE는 응답 코드로 신규 가입 여부 구분 가능 (환영 메시지 등).
         */
        post: operations["google_login_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 닉네임 변경
         * @description 현재 인증된 사용자의 닉네임을 변경한다.
         */
        patch: operations["update_me_nickname_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 비밀번호 변경 (email 사용자만)
         * @description 현재 인증된 사용자의 비밀번호를 변경한다.
         *
         *     google 사용자는 400 (auth_provider 정책 위반).
         *     old_password 불일치 시 401 (토큰 탈취자 방지).
         */
        patch: operations["update_me_password_api_v1_users_me_password_patch"];
        trace?: never;
    };
    "/api/v1/users/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bookmarks
         * @description 사용자의 북마크 목록을 최신순(bookmark_id DESC)으로 반환.
         *
         *     선택적 필터: thread_id, pin_type.
         *     cursor 페이지네이션: bookmark_id 기반 (BIGSERIAL → 단조 증가).
         */
        get: operations["list_bookmarks_api_v1_users_me_bookmarks_get"];
        put?: never;
        /**
         * Create Bookmark
         * @description 북마크 생성.
         *
         *     message_id가 messages 테이블에 존재하지 않으면 FK 제약으로 DB 오류 → 422 반환.
         */
        post: operations["create_bookmark_api_v1_users_me_bookmarks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/bookmarks/{bookmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Bookmark
         * @description 북마크 소프트 삭제 (is_deleted=true).
         *
         *     소유권 검증: 다른 사용자의 북마크 → 404 (정보 노출 방지).
         *     이미 삭제된 북마크 → 404.
         */
        delete: operations["delete_bookmark_api_v1_users_me_bookmarks__bookmark_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chats
         * @description 사용자의 채팅 목록을 최신순으로 반환.
         *
         *     cursor 페이지네이션:
         *       - 첫 요청: cursor 없이 → 최신 limit건 반환
         *       - 다음 페이지: 응답의 next_cursor를 cursor에 넣어서 재요청
         *       - next_cursor가 null이면 마지막 페이지
         *
         *     왜 offset이 아닌 cursor?
         *       - offset은 중간에 데이터가 추가/삭제되면 중복/누락 발생
         *       - cursor(updated_at)는 정렬 기준이므로 안정적
         */
        get: operations["list_chats_api_v1_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat
         * @description 특정 채팅의 메타데이터만 반환. 메시지는 포함하지 않음.
         *
         *     메시지는 별도 API (GET /chats/{thread_id}/messages)로 분리.
         *     이유: 메시지가 수백 건일 때 메타데이터 조회에 전부 끌려오면 낭비.
         */
        get: operations["get_chat_api_v1_chats__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat
         * @description 대화를 소프트 삭제. 물리 삭제가 아닌 is_deleted=true 마킹.
         *
         *     왜 소프트 삭제?
         *       - messages는 append-only (불변식 #3) → DELETE 불가
         *       - 물리 DELETE하면 FK CASCADE가 messages를 삭제해버림
         *       - is_deleted=true로 마킹만 하면 messages는 보존됨
         *       - 목록 조회에서 is_deleted=false 필터로 안 보이게 처리
         *
         *     204 No Content: 성공 시 응답 본문 없음 (REST 관례).
         */
        delete: operations["delete_chat_api_v1_chats__thread_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Chat Title
         * @description 대화 제목을 수정. updated_at도 갱신되어 채팅 목록 정렬에 반영됨.
         *
         *     RETURNING으로 UPDATE 결과를 바로 반환 — 추가 SELECT 불필요.
         */
        patch: operations["update_chat_title_api_v1_chats__thread_id__patch"];
        trace?: never;
    };
    "/api/v1/chats/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description 특정 대화의 메시지 목록을 오래된 순(ASC)으로 반환.
         *
         *     왜 ASC?
         *       - 채팅 UI에서 위=오래된, 아래=최신이 자연스러움
         *       - cursor는 message_id 기반 (BIGSERIAL이라 정렬 안정적)
         *
         *     messages 테이블은 append-only (불변식 #3):
         *       - 이 함수는 SELECT만 수행
         *       - INSERT는 SSE 핸들러가 담당
         *       - UPDATE/DELETE는 이 모듈 어디에도 없음
         */
        get: operations["list_messages_api_v1_chats__thread_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat Stream
         * @description 메인 채팅 SSE 엔드포인트.
         *
         *     Args:
         *         request: FastAPI Request (disconnect 감지용).
         *         thread_id: 대화 스레드 ID.
         *         query: 사용자 쿼리 텍스트.
         *         token: JWT 토큰 (query parameter fallback).
         *         retry: True이면 응답 재생성 (user INSERT 생략, append-only 준수).
         */
        get: operations["chat_stream_api_v1_chat_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Calendar Auth Url
         * @description Google Calendar 동의 URL 발급.
         *
         *     JWT 인증 필수. 반환된 auth_url로 사용자를 리다이렉트하면
         *     구글 동의 후 /callback이 자동 호출된다.
         */
        get: operations["google_calendar_auth_url_api_v1_auth_google_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/calendar/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Calendar Callback
         * @description Google OAuth 콜백 — code 수신 → refresh_token 저장.
         *
         *     구글이 직접 호출하는 엔드포인트. JWT 인증 없음.
         *     user_id는 state 파라미터 서명 검증으로 추출.
         */
        get: operations["google_calendar_callback_api_v1_auth_google_calendar_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{thread_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 대화 공유 링크 생성
         * @description share_token 발급. 소유권 검증 후 shared_links INSERT.
         */
        post: operations["create_share_link_api_v1_chats__thread_id__share_post"];
        /**
         * 공유 링크 해제
         * @description 해당 thread의 모든 활성 공유 링크를 소프트 삭제.
         */
        delete: operations["delete_share_link_api_v1_chats__thread_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared/{share_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공유 대화 조회 (읽기 전용)
         * @description 인증 없이 공유된 대화를 조회. is_deleted=false + 만료 미도래 확인.
         */
        get: operations["get_shared_conversation_shared__share_token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — 컨테이너 헬스체크와 CI 확인용.
         *
         *     Kubernetes/Docker에서 이 엔드포인트를 주기적으로 호출해서
         *     서버가 살아있는지 확인한다.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookmarkCreateRequest */
        BookmarkCreateRequest: {
            /** Thread Id */
            thread_id: string;
            /** Message Id */
            message_id: number;
            /**
             * Pin Type
             * @enum {string}
             */
            pin_type: "place" | "event" | "course" | "analysis" | "general";
            /** Preview Text */
            preview_text?: string | null;
        };
        /** BookmarkCreateResponse */
        BookmarkCreateResponse: {
            /** Bookmark Id */
            bookmark_id: number;
            /** Thread Id */
            thread_id: string;
            /** Message Id */
            message_id: number;
            /**
             * Pin Type
             * @enum {string}
             */
            pin_type: "place" | "event" | "course" | "analysis" | "general";
            /** Preview Text */
            preview_text?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookmarkItem */
        BookmarkItem: {
            /** Bookmark Id */
            bookmark_id: number;
            /** Thread Id */
            thread_id: string;
            /** Message Id */
            message_id: number;
            /**
             * Pin Type
             * @enum {string}
             */
            pin_type: "place" | "event" | "course" | "analysis" | "general";
            /** Preview Text */
            preview_text?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookmarkListResponse */
        BookmarkListResponse: {
            /** Items */
            items?: components["schemas"]["BookmarkItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ChatDetailResponse
         * @description 채팅 메타데이터. 메시지는 포함하지 않음 (별도 API).
         *
         *     FE가 대화를 열 때:
         *       1) 이 API로 제목/시간 로딩
         *       2) /messages API로 메시지 별도 로딩
         */
        ChatDetailResponse: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChatListItem
         * @description 채팅 목록에서 한 줄 = 이 모델 하나.
         *
         *     사이드바에 표시할 최소 정보만 담는다:
         *       - thread_id: 대화 고유 식별자 (클릭 시 상세 조회에 사용)
         *       - title: 대화 제목 (자동 생성 또는 사용자 수정)
         *       - last_message: 마지막 메시지 미리보기 (아직 미구현, SSE 연동 후 추가)
         *       - updated_at: 마지막 활동 시간 (정렬 기준)
         */
        ChatListItem: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title?: string | null;
            /** Last Message */
            last_message?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ChatListResponse
         * @description 채팅 목록 API의 전체 응답.
         *
         *     cursor 페이지네이션:
         *       - items: 이번 페이지의 채팅 목록
         *       - next_cursor: 다음 페이지 요청 시 사용할 값. null이면 마지막 페이지.
         */
        ChatListResponse: {
            /** Items */
            items?: components["schemas"]["ChatListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ChatUpdateRequest
         * @description 대화 제목 수정 요청 body.
         *
         *     FE에서 보내는 JSON: {"title": "새 제목"}
         *     Pydantic이 자동으로 파싱하고, title이 없거나 타입이 다르면 422 반환.
         */
        ChatUpdateRequest: {
            /** Title */
            title: string;
        };
        /**
         * ChatUpdateResponse
         * @description 대화 제목 수정 후 응답.
         *
         *     UPDATE ... RETURNING으로 DB에서 바로 가져온 결과.
         */
        ChatUpdateResponse: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GoogleLoginRequest
         * @description POST /api/v1/auth/google 요청 본문.
         *
         *     FE의 Google Identity Services에서 받은 id_token을 그대로 전달.
         *     BE가 google-auth로 서명/iss/aud 검증.
         */
        GoogleLoginRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description POST /api/v1/auth/login 요청 본문.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MessageItem
         * @description 단일 메시지 = 이 모델 하나.
         *
         *     필드:
         *       - message_id: DB PK (BIGSERIAL). cursor 페이지네이션에 사용.
         *       - role: "user" (사용자 입력) 또는 "assistant" (AI 응답)
         *       - blocks: 응답 블록 배열. JSONB로 저장된 16종 블록 (place, events, chart 등).
         *                 예: [{"type": "text_stream", "content": "홍대에는..."}, {"type": "places", "items": [...]}]
         *       - created_at: 메시지 생성 시각
         */
        MessageItem: {
            /** Message Id */
            message_id: number;
            /** Role */
            role: string;
            /** Blocks */
            blocks?: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageListResponse
         * @description 메시지 목록 API의 전체 응답.
         *
         *     ChatListResponse와 같은 cursor 패턴:
         *       - next_cursor가 null이면 마지막 페이지
         *       - 있으면 다음 요청에 ?cursor=값 으로 넘김
         */
        MessageListResponse: {
            /** Items */
            items?: components["schemas"]["MessageItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * MessageRange
         * @description 공유 메시지 범위. null이면 전체 대화.
         */
        MessageRange: {
            /** From Message Id */
            from_message_id?: number | null;
            /** To Message Id */
            to_message_id?: number | null;
        };
        /**
         * NicknameUpdate
         * @description PATCH /api/v1/users/me 요청 본문.
         */
        NicknameUpdate: {
            /** Nickname */
            nickname: string;
        };
        /**
         * PasswordUpdate
         * @description PATCH /api/v1/users/me/password 요청 본문.
         *
         *     auth_provider='email' 사용자만 사용 가능. google 사용자는 400.
         */
        PasswordUpdate: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ShareCreateRequest
         * @description 공유 링크 생성 요청.
         */
        ShareCreateRequest: {
            message_range?: components["schemas"]["MessageRange"] | null;
        };
        /**
         * ShareCreateResponse
         * @description 공유 링크 생성 응답.
         */
        ShareCreateResponse: {
            /** Share Token */
            share_token: string;
            /** Share Url */
            share_url: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * SharedConversationResponse
         * @description 공유 대화 조회 응답 (인증 불필요).
         */
        SharedConversationResponse: {
            /** Thread Title */
            thread_title?: string | null;
            /** Messages */
            messages?: components["schemas"]["SharedMessage"][];
        };
        /**
         * SharedMessage
         * @description 공유 대화의 개별 메시지.
         */
        SharedMessage: {
            /** Role */
            role: string;
            /** Blocks */
            blocks?: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at: string;
        };
        /**
         * SignupRequest
         * @description POST /api/v1/auth/signup 요청 본문.
         */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Nickname */
            nickname?: string | null;
        };
        /**
         * TokenResponse
         * @description signup/login/google 공통 응답 — JWT + 사용자 식별 정보.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** Nickname */
            nickname?: string | null;
        };
        /**
         * UserResponse
         * @description 사용자 프로필 응답 (PATCH /me 등).
         */
        UserResponse: {
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** Nickname */
            nickname?: string | null;
            /** Auth Provider */
            auth_provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description 기존 Google 사용자 로그인 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description 신규 Google 사용자 자동 가입 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효하지 않은 Google 토큰 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 다른 방식으로 가입된 이메일 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_nickname_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_password_api_v1_users_me_password_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookmarks_api_v1_users_me_bookmarks_get: {
        parameters: {
            query?: {
                /** @description 특정 대화의 북마크만 필터 */
                thread_id?: string | null;
                /** @description 핀 종류 필터 */
                pin_type?: ("place" | "event" | "course" | "analysis" | "general") | null;
                /** @description 페이지네이션 커서 (bookmark_id) */
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bookmark_api_v1_users_me_bookmarks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookmarkCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bookmark_api_v1_users_me_bookmarks__bookmark_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bookmark_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_v1_chats_get: {
        parameters: {
            query?: {
                /** @description 페이지네이션 커서 (updated_at ISO) */
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_api_v1_chats__thread_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_api_v1_chats__thread_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_chat_title_api_v1_chats__thread_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_chats__thread_id__messages_get: {
        parameters: {
            query?: {
                /** @description 페이지네이션 커서 (message_id) */
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_get: {
        parameters: {
            query: {
                thread_id: string;
                query: string;
                token?: string | null;
                retry?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_calendar_auth_url_api_v1_auth_google_calendar_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_calendar_callback_api_v1_auth_google_calendar_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_link_api_v1_chats__thread_id__share_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ShareCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_share_link_api_v1_chats__thread_id__share_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_conversation_shared__share_token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: {
                verbose?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
